CREATE TABLE ROOT.IDENTITIES (
	UID VARCHAR(100),
	DISPLAY_NAME VARCHAR(100),
	EMAIL VARCHAR(100)
) ;

SELECT UID, DISPLAY_NAME, EMAIL
FROM ROOT.IDENTITIES;

INSERT INTO ROOT.IDENTITIES
(UID, DISPLAY_NAME, EMAIL)
VALUES('', '', '');

UPDATE ROOT.IDENTITIES
SET UID='', DISPLAY_NAME='', EMAIL='';

DELETE FROM  ROOT.IDENTITIES
WHERE UID='' AND DISPLAY_NAME='' AND EMAIL='';

DELETE FROM  ROOT.IDENTITIES
WHERE UID='' AND DISPLAY_NAME='' AND EMAIL='';

